timezone: America/Denver
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      author: "Eric Parshall"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"
